export {
  createTreatyQuery,
  type CreateHelpersOptions,
  type CreateTreatyQueryFactory,
  type CreateTreatyQueryOptions,
  type TreatyQueryClient,
  type TreatyQueryRoot,
} from "./create-treaty-query.js";
export {
  TreatyQueryError,
  TreatyQueryErrorMappingError,
  type TreatyQueryErrorOptions,
  type TreatyQueryErrorMapper,
} from "./error.js";
export { routeSegment } from "./route.js";
export type {
  MutationBody,
  MutationData,
  MutationError,
  MutationFactoryResult,
  MutationMethodName,
  MutationOperation,
  MutationOperationOptions,
  MutationRequest,
  OptionalMutationOperation,
  RequiredMutationOperation,
} from "./mutation.js";
export type {
  GetData,
  GetError,
  GetInput,
  GetOperation,
  GetOperationOptions,
  GetRequest,
  OptionalGetOperation,
  RequiredGetOperation,
  StaticGetData,
  StaticGetError,
  StaticGetOperation,
  StaticTreatyQueryHelpers,
  TreatyQueryHelpers,
} from "./static-helpers.js";
export type {
  CacheScopeProvider,
  CacheScopeProviderProps,
  OptionalUseMutationOperation,
  OptionalUseQueryOperation,
  RequiredUseMutationOperation,
  RequiredUseQueryOperation,
  StaticTreatyQueryHooks,
  StaticUseQueryOperation,
  TreatyQueryHooks,
  TreatyQueryProvider,
  TreatyQueryProviderProps,
  UseMutationOperation,
  UseQueryOperation,
} from "./react.js";
export type {
  CacheUtilityScopeOptions,
  GetUtilities,
  OptionalGetUtilities,
  RequiredGetUtilities,
  TreatyEnsureDataOptions,
  TreatyInvalidateOptions,
  TreatyQueryRouteUtilitiesFor,
  TreatyQueryUtils,
  TreatyRouteUtilities,
  TreatySetDataOptions,
} from "./utils.js";
export type {
  CacheScope,
  GetQueryOptions,
  GetQueryOptionsInput,
  MutationOptionsInput,
  SerializableValue,
  StaticGetQueryOptions,
  StaticGetQueryOptionsInput,
  TreatyQueryKey,
  TreatyMutationKey,
  TreatyMutationMethod,
  TreatyMutationOperation,
  TreatyMutationOptions,
  TreatyQueryOperation,
  TreatyQueryParameterEntry,
  TreatyQueryParameterSegment,
  TreatyQueryPathSegment,
  TreatyQueryPrefix,
  TreatyQueryRouteKey,
  TreatyQueryScope,
  TreatyQuerySemanticInput,
} from "./types.js";

export const version: "0.1.1" = "0.1.1";
